import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Disable Developer Tools
              document.addEventListener('keydown', function(e) {
                // F12
                if (e.key === 'F12') {
                  e.preventDefault();
                  return false;
                }
                
                // Ctrl+Shift+I (Chrome DevTools)
                if (e.ctrlKey && e.shiftKey && e.key === 'I') {
                  e.preventDefault();
                  return false;
                }
                
                // Ctrl+Shift+J (Chrome Console)
                if (e.ctrlKey && e.shiftKey && e.key === 'J') {
                  e.preventDefault();
                  return false;
                }
                
                // Ctrl+U (View Source)
                if (e.ctrlKey && e.key === 'u') {
                  e.preventDefault();
                  return false;
                }
                
                // Ctrl+Shift+C (Chrome Elements)
                if (e.ctrlKey && e.shiftKey && e.key === 'C') {
                  e.preventDefault();
                  return false;
                }
              });
              
              // Disable right-click context menu
              document.addEventListener('contextmenu', function(e) {
                e.preventDefault();
                return false;
              });
              
              // Disable Ctrl+Shift+I through keyup as well
              document.addEventListener('keyup', function(e) {
                if (e.ctrlKey && e.shiftKey && e.key === 'I') {
                  e.preventDefault();
                  return false;
                }
              });
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
